import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Toaster } from "@/components/ui/sonner";
import NavBar from "@/components/ui/nav-bar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// named export -- must import with exact name
export const metadata: Metadata = {
  title: "JVNT",
  description: "Generated by create next app",
};

// default export -- can import with any name
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <NavBar />

        <h1 className="text-6xl p-8">JVNT</h1>

        {children}

        <Toaster position="top-left" richColors />

        <footer className="p-8">&copy; JVT 2026</footer>

        {/* TODO: add github icon */}
      </body>
    </html>
  );
}
