import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Toaster } from "@/components/ui/sonner";
import NavBar from "@/components/ui/nav-bar";
import Footer from "@/components/ui/footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// named export -- must import with exact name
export const metadata: Metadata = {
  title: "joelvt",
  description: "Generated by create next app",
};

// default export -- can import with any name
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {/* could try using items-center-safe safe here */}
        <div className="p-1 flex-col items-center-safe justify-center">
          {/* <h1 className="text-6xl mt-6 mx-4 flex justify-center">joelvt</h1> */}

          <NavBar />

          {/* TODO: map page names to header divs */}
          {/* {} */}

          {children}

          <Toaster position="top-left" richColors />

          <Footer />
        </div>
      </body>
    </html>
  );
}
